# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39663fcc90f575339d137825c9a4a7bc57eacd81d1b927fbd37ab2de2d952804dda24ffa111101011ef9787b4bc969c819bf2c02d00dd4424f5fe1fe464d6456

test:
  secret_key_base: 589c45a3a7e182cfab979f308420ef6afaadc74b85fa8eb1445a8b88f5e3d12f7a52165d2629514adbe0f7a6ed9d3b511b702c396e36f4007c00a2de62bd5a0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
